### ISSUE TITLE
MansOS IDE sometimes fails to start

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IECS/MansOS#11]
```
MansOS IDE can sometimes fail to start without showing any error, it is 
functioning as process, but GUI ain't showing.

Temporary solution, until I locate the problem, is to delete config.cfg file 
from MansOS IDE directory.
```

Original issue reported on code.google.com by `janis.ju...@gmail.com` on 28 May 2013 at 2:08

**Comment by elomage** [comment]
Well, the config file should be stored elsewhere, because this directory may be open for read-only...
Fix by moving the config file to the workspace.
